---
- name: Include pre-check tasks
  ansible.builtin.include_tasks: precheck.yml

- name: Include CSR generation tasks
  ansible.builtin.include_tasks: generate_csr.yml

- name: Include post-check tasks
  ansible.builtin.include_tasks: postcheck.yml
