---
- name: Include pre-check tasks
  ansible.builtin.include_tasks: precheck.yml

- name: Include certificate issuance tasks
  ansible.builtin.include_tasks: issue.yml

- name: Include post-check tasks
  ansible.builtin.include_tasks: postcheck.yml
